# Generated by Django 3.0.3 on 2020-02-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_match_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
        migrations.AddField(
            model_name='match',
            name='deck',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='mformat',
            field=models.CharField(default='Legacy', max_length=100),
        ),
        migrations.AlterField(
            model_name='league',
            name='deck',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='league',
            name='mformat',
            field=models.CharField(default='Legacy', max_length=100),
        ),
    ]
