# Generated by Django 3.0.3 on 2020-02-18 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='deck',
        ),
    ]
